services:
  api:
    container_name: firesense-webapi
    build:
        dockerfile: Dockerfile
        context: .
    ports:
      - 4652:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: ["firesense-api-sql"]
    networks:
      firesense-networks:
    
  firesense-api-sql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment: 
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Aps@2025140612#"
    volumes:
      - "firesense-api-mssql-azure-edge:/var/opt/mssql"
    networks:
      firesense-networks:
        aliases:
          - "sql"   

volumes:
  firesense-api-mssql-azure-edge:

networks:
  firesense-networks:
    driver: bridge